@startuml
skinparam style strictuml
skinparam backgroundColor transparent
skinparam defaultFontName Arial
skinparam style strictuml

skinparam noteFontName Courier New

hide empty members
interface Target {
  {abstract} Request()
}
class Adapter implements Target {
  Request()
}
note right of Adapter::Request
adaptee -> SpecificRequest()
end note
class Adaptee {
  SpecificRequest()
}

Adaptee <-u- Adapter : adaptee

class Client {
}
Client -r-> Target
@enduml